export const autocompleteCities = [
    "Plovdiv",
    "Sofia",
    "Burgas",
    "Varna",
    "Pleven",
    "Veliko Tarnovo",
    "Vidin",
    "Strelcha",
    "Tokyo",
    "New York",
    "London",
    "Paris",
    "Los Angeles",
    "Chicago",
    "Las Vegas",
    "Miami",
    "San Francisco",
    "Sydney",
    "Singapore",
    "Hong Kong",
    "Bangkok",
    "Dubai",
    "Rome",
    "Barcelona",
    "Berlin",
    "Moscow",
    "Cairo",
    "Amsterdam",
    "Buenos Aires",
    "Mumbai",
    "Shanghai",
    "Beijing",
    "Prague",
    "Vienna",
    "Toronto",
    "Mexico City",
    "Cape Town",
    "Vancouver",
    "Madrid",
    "Zurich",
    "Athens",
    "Budapest",
    "Kyoto",
    "Kuala Lumpur",
    "Oslo",
    "Copenhagen",
    "Stockholm",
    "Helsinki",
    "Auckland",
    "Dublin",
    "Warsaw",
    "Lisbon",
    "Wellington",
    "Edinburgh",
    "Lima",
    "Manila",
  ];

export const popularCities = ["Plovdiv", "Sofia", "Varna", "New York", "Paris", "Tokyo", "Sydney"];